#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform PushConstants {
    uint K; // in_features
    uint N; // out_features
} pc;

layout(std430, binding = 0) readonly buffer InputX {
    float x[];
};

layout(std430, binding = 1) readonly buffer WeightsW {
    float w[];
};

layout(std430, binding = 2) writeonly buffer OutputY {
    float y[];
};

void main() {
    uint row = gl_GlobalInvocationID.x;
    if (row >= pc.N) return;

    uint w_offset = row * pc.K;
    float sum = 0.0;
    for (uint col = 0; col < pc.K; col++) {
        sum += w[w_offset + col] * x[col];
    }

    y[row] = sum;
}
